
EXAMPLE=wavesolver
CPP_SRC=main.cpp wavesolver.cpp wavesolver_serial.cpp 
ISPC_SRC=wavesolver.ispc
#ISPC_IA_TARGETS=sse2-i32x4,sse4-i32x8,avx1-i32x16,avx2-f32x8
ISPC_IA_TARGETS=host
#ISPC_IA_TARGETS=generic-4
ISPC_ARM_TARGETS=neon

include common.mk
